### ISSUE TITLE
Including BS3 in Template <style></style> ?

### ISSUE THREAD

**Issue by ai10** [handmadeadv/vector#3]
Consider separating css out of the Templates.html files?

I'm actually going through now and trying to get it functional with minimal specific styling. 
I.e. using just BS3 standard components so that styling can be done more independently.

Also not sure if unique vectorLayout is really needed since it basically just {{yield}}

changing routes to renderTemplates: 'vectorNav' to 'navigation'

**Comment by handmadeadv** [comment]
Bootstrap was included into templates.html files as a 'packaged' style which doesn't influence the main website style. We are researching alternative methods such generate a .css file inside the public folder, but it will take time.

The vectorLayout is meant as a separate layout for the admin, where you will use another layout, with its own {{yeld}}, for the main website.

Also, we don't wont to get in the way with common template names. 'navigation' could be already used on a frontend website. We shall update modules template names as well since 'text' and 'textarea' are way too common.

We are open to suggestion about improving the above topics

**Comment by handmadeadv** [comment]
The css is now served as static assets. Developers have now some options for their fronted:
- include bootstrap from the vector package at url/packages/vector/themes/bootstrap.css
- use the bootstrap 3 package (bootstrap will be duplicated for the admin, but nothing horrible should happen)
- avoid completely bootstrap
