### ISSUE TITLE
Starting meteor without "--settings" property

### ISSUE THREAD

**Issue by matteodem** [handmadeadv/vector#9]
Hello there

I'm on a more or less pretty big project and I find your admin package quite interesting. Is there a way to load the settings programatically? (Instead of using "--settings") 

Also are you planning on changing any of the API for adding custom modules to the admin? And the last question of those three would be why is the password in the login showed in plain text?

Greetings

**Comment by matteodem** [comment]
ping

**Comment by handmadeadv** [comment]
Hello matteodem.
Currently there is not a method to skip the settings,json.
It also depends on when do you want to load these settings.
The settings have to be loaded before anything else in order to create collections and helpers. If you have some idea we can make some experiment.

The API will not change regarding the creation of modules, and the names of the helpers. The new Meteor UI will probably bring some internal refactoring.

**Comment by matteodem** [comment]
Okay, thanks for your answer. I'll have a look and will write you if there's any way of doing this.
